#!/usr/bin/env bash
# scripts/test-execution-reporting.sh - Parse test results and post PR comments
# Voert tests uit en rapporteert resultaten als PR comment
set -uo pipefail

source "$(dirname "$0")/../lib/config.sh"
source "$(dirname "$0")/../lib/telegram.sh"

log "=== Test Execution Reporting ==="

# Configuratie
TR_ENABLED="${TR_ENABLED:-yes}"
TR_DRY_RUN="${TR_DRY_RUN:-no}"
TR_REPOS="${TR_REPOS:-}"

# Function: run tests for a repo
run_tests() {
  local repo="$1"
  local repo_dir="$REPOS_DIR/${repo//\//_}"
  
  if [ ! -d "$repo_dir" ]; then
    log "⚠️  Repo niet gekloond: $repo"
    return 1
  fi
  
  log "Running tests for $repo..."
  cd "$repo_dir"
  
  local test_results=""
  local passed=0
  local failed=0
  local skipped=0
  
  # Check for different test runners
  # Python tests
  if [ -f "pytest.ini" ] || [ -f "setup.cfg" ] || [ -f "pyproject.toml" ] || find . -name "test_*.py" -o -name "*_test.py" | head -1; then
    log "  Running pytest..."
    if [ "$TR_DRY_RUN" != "yes" ]; then
      test_output=$(python3 -m pytest --tb=short -q 2>&1 || true)
      
      # Parse results
      passed=$(echo "$test_output" | grep -oE '[0-9]+ passed' | grep -oE '[0-9]+' || echo "0")
      failed=$(echo "$test_output" | grep -oE '[0-9]+ failed' | grep -oE '[0-9]+' || echo "0")
      skipped=$(echo "$test_output" | grep -oE '[0-9]+ skipped' | grep -oE '[0-9]+' || echo "0")
      
      if [ "$failed" -gt 0 ]; then
        # Get failure details
        test_results=$(echo "$test_output" | grep -A2 "FAILED\|ERROR" | head -20)
      fi
    else
      log "    [DRY RUN] Would run pytest"
    fi
  fi
  
  # JavaScript tests
  if [ -f "package.json" ] && grep -q '"jest\|"vitest\|"mocha' package.json 2>/dev/null; then
    log "  Running JS tests..."
    if [ "$TR_DRY_RUN" != "yes" ]; then
      test_output=$(npm test -- --json 2>/dev/null || npx jest --json 2>/dev/null || true)
      
      if [ -n "$test_output" ]; then
        passed=$(echo "$test_output" | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  print(data.get('numPassedTests', 0))
except:
  print(0)
" 2>/dev/null || echo "0")
        
        failed=$(echo "$test_output" | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  print(len(data.get('testResults', [])) - data.get('numPassedTests', 0) if data.get('success') == False else 0)
except:
  print(0)
" 2>/dev/null || echo "0")
      fi
    else
      log "    [DRY RUN] Would run JS tests"
    fi
  fi
  
  # Shell script tests
  if find . -name "*.sh" -type f | head -1; then
    log "  Checking shell scripts..."
    
    # Syntax check all shell scripts
    syntax_errors=0
    while IFS= read -r script; do
      if ! bash -n "$script" 2>/dev/null; then
        syntax_errors=$((syntax_errors + 1))
        test_results="${test_results}\n- ❌ Syntax error in $script"
      fi
    done < <(find . -name "*.sh" -type f)
    
    if [ "$syntax_errors" -eq 0 ]; then
      log "    ✅ All shell scripts pass syntax check"
    else
      log "    ❌ $syntax_errors shell scripts have syntax errors"
    fi
  fi
  
  echo "PASSED:$passed FAILED:$failed SKIPPED:$skipped RESULTS:$test_results"
  return 0
}

# Function: post test results to PR
post_test_results() {
  local repo="$1"
  local pr_number="$2"
  local results="$3"
  
  local passed failed skipped
  passed=$(echo "$results" | grep -oP 'PASSED:\K[0-9]+' || echo "0")
  failed=$(echo "$results" | grep -oP 'FAILED:\K[0-9]+' || echo "0")
  skipped=$(echo "$results" | grep -oP 'SKIPPED:\K[0-9]+' || echo "0")
  
  local comment
  comment=$(cat << EOF
## 🧪 Automated Test Results

| Metric | Count |
|--------|-------|
| ✅ Passed | $passed |
| ❌ Failed | $failed |
| ⏭️ Skipped | $skipped |

<details>
<summary>Failure details</summary>

\`\`\`
$(echo "$results" | grep -oP 'RESULTS:\K.*' | sed 's/\\n/\n/g')
\`\`\`
</details>

---
*Auto-generated by Fleet Manager Test Execution Reporting*
EOF
)
  
  log "Posting test results to PR #$pr_number..."
  
  if [ "$TR_DRY_RUN" = "yes" ]; then
    log "  [DRY RUN] Would post comment"
    return 0
  fi
  
  gh api "repos/$repo/issues/$pr_number/comments" \
    -X POST \
    -f "body=$comment" \
    2>/dev/null || log "  ❌ Post comment mislukt"
}

# Function: get open PRs for a repo
get_open_prs() {
  local repo="$1"
  
  gh pr list --repo "$repo" --state open --json number,title \
    --jq '.[] | "\(.number)|\(.title)"' \
    2>/dev/null || echo ""
}

# Hoofdlogica
if [ "$TR_ENABLED" != "yes" ]; then
  log "Test execution reporting uitgeschakeld"
  exit 0
fi

if [ -n "$TR_REPOS" ]; then
  IFS=',' read -ra TRACKED_REPOS <<< "$TR_REPOS"
else
  TRACKED_REPOS=("${KEY_REPOS[@]}")
fi

for kr in "${TRACKED_REPOS[@]}"; do
  log "Processing $kr..."
  
  # Run tests
  results=$(run_tests "$kr")
  log "  Results: $results"
  
  # Get open PRs and post results
  prs=$(get_open_prs "$kr")
  
  if [ -n "$prs" ]; then
    echo "$prs" | while IFS='|' read -r number title; do
      [ -z "$number" ] && continue
      post_test_results "$kr" "$number" "$results"
    done
  fi
done

log "=== Test Execution Reporting klaar ==="
